# 1: Config (Usually used, doesn't need to set 'database-server-settings' values)
# 2: Redis (Redis database, needs to set 'database-server-settings' values)
# 3: MySQL (Doesn't support now)
# Default: 1
database-type: 1

# When you set 'database-type' to any type of database(like Redis and MySQL), you need to set this setting
database-server-settings:
  # Database server host name. It can be an ip address also a domain name
  host: "localhost"
  # Database server port name. For Redis, it usually was '6379'. For MySQL, '3306' is the default
  port: 0
  # Database server user name. For Redis, it usually was 'null'(empty string). For MySQL, 'root' is the default
  user: ""
  # Database server user password. For Redis, it defaults 'null'(empty string).
  password: ""
  # Database id. For Redis, it means which database will be used by Money plugin(because Redis can have multi databases).
  # For MySQL, it represents database name
  id: 0

# Whether to use the multi thread to handle command (i.e. when using a command, server will not be abnormal. But may be due to a database query causes (1 ~ 5 seconds) delay.
# If you do not understand that, please use default value.
# Default: true
command-threaded: true

# 1st Currency
# Default: Coin
money-unit-1: "Coin"

# If false, players can't use 2st currency
# Default: true
enable-unit-2: true

# 2nd Currency.  (Only 1st currency can deposit in the bank)
# Default: Point
money-unit-2: "Point"

# Bank interest.
# Default: 0.0003
bank-interest-value: "0.0003"

# Bank interest calculation time. (Real time) (Unit: sec)
# Default: 7200
bank-interest-time: "7200"

# Please do not modify that.
bank-time: "0"

# The number of initial money players entering the server for the first time
# Default: 1000
initial-money-1: "1000"

# The number of initial money players entering the server for the first time
# Default: 0
initial-money-2: "0"

# The initial bank savings of players entering the server for the first time
# Default: 0
initial-bank-money: "0"

# When paying the first currency, the player is the lowest.
# Default: 1000
pay-1-limit: "1000"

# When paying the second currency, the player is the lowest.
# Default: 1000
pay-2-limit: "1000"